# Generated by Django 5.0.3 on 2025-01-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodDoctor', '0002_alter_pacjent_miasto_alter_pacjent_ulica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizyta',
            name='zalecenia',
        ),
        migrations.AddField(
            model_name='wizyta',
            name='powod',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
