# Generated by Django 5.0.3 on 2025-05-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farbyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farba',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='farba',
            name='kolor',
            field=models.CharField(max_length=100),
        ),
    ]
