# Generated by Django 4.2.20 on 2025-03-23 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ryby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField()),
                ('wystepowanie', models.TextField()),
                ('styl_zycia', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Okres_ochronny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_miesiaca', models.IntegerField()),
                ('do_miesiaca', models.IntegerField()),
                ('wymiar_ochronny', models.IntegerField()),
                ('ryby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rybyapp.ryby')),
            ],
        ),
    ]
